console.log("Hello Everyone !!");
document.write("Hello Everyone _Browser !!");
var general;
console.log(general);
general=6;
console.log(typeof general);
general="Hi";
console.log(typeof general);
general='a';
console.log(typeof general);
general=true;
console.log(typeof general);
general=null;
console.log(typeof general);
general=[2,4,6,8,10];
console.log(typeof general);
general=new Array(12,25,34);
console.log(general.length);
var num1=prompt("Enter some value");
console.log("By default all data entered in prompt will be of type - "+typeof num1);
console.log(num1+10);
console.log(parseInt(num1)+10);
